version: '3'
services:
  db:
    container_name: mysql_db
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_EXTERNAL_PORT}:80"
    depends_on:
      - db

  app:
    container_name: tezosmarket_api
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${SERVER_EXTERNAL_PORT}:8000
    depends_on:
      - db